%\VignetteIndexEntry{RTCAtransformation: Discussion of transformation methods of RTCA data}
%\VignetteDepends{}
%\VignettePackage{}

\documentclass[11pt]{article}

\usepackage{mathptmx}	 
\usepackage[scaled=0.92]{helvet}
\usepackage{courier}
\usepackage{multirow}
\usepackage{url}
\renewcommand{\multirowsetup}{\centering}

\usepackage{times}
\usepackage{hyperref}
\usepackage{geometry}
\usepackage{longtable}
\usepackage[pdftex]{graphicx}
\SweaveOpts{keep.source=TRUE,eps=FALSE,pdf=TRUE,prefix=FALSE} 

% R part
\newcommand{\todo}[2]{\textit{\textbf{To do:} (#1) #2}}
\newcommand{\fixme}[2]{\textit{\textbf{FIXME:} (#1) #2}}
\newcommand{\R}[1]{{\textsf{#1}}}
\newcommand{\Rfunction}[1]{{\texttt{#1}}}
\newcommand{\Robject}[1]{{\texttt{#1}}}
\newcommand{\Rpackage}[1]{{\textit{#1}}}
\newcommand{\Rclass}[1]{{\textit{#1}}}
\newcommand{\Metas}[1]{{\texttt{#1}}}
\newcommand{\myincfig}[3]{%
  \begin{figure}[htbp]
    \begin{center}
      \includegraphics[width=#2]{#1}
      \caption{\label{#1}#3}
    \end{center}
  \end{figure}
}

% trademark, copyright and registered
\def\TReg{\textsuperscript{\textregistered}}
\def\TCop{\textsuperscript{\textcopyright}}
\def\TTra{\textsuperscript{\texttrademark}}
\def\xSys{xCELLigence\TTra System }

\begin{document}
\setkeys{Gin}{width=0.9\textwidth}
\title{RTCAtransformation: Discussion of transformation methods of RTCA data}
\author{Jitao David Zhang}
\maketitle

\begin{abstract}
  The \xSys provides a dimentionless parameter Cell Index (CI) to
  reflect the biological status of the monitored cells. In this
  vignette we discuss the concept of the cell index briefly, and
  introduces several transformation approaches to allow statistical
  inferences of the RTCA assays.
\end{abstract}

\section{Introduction}

First we load packages:
<<lib, echo=TRUE>>=
library(xtable)
library(RTCA)
@ 

And we load a dataset (with its annotation) provided with the package as example:
<<dataset, echo=TRUE>>=
ofile <-  system.file("extdata/testOutput.csv", package="RTCA")
pfile <- system.file("extdata/testOutputPhenoData.csv", package="RTCA")
pData <- read.csv(pfile, sep="\t", row.names="Well")
metaData <- data.frame(labelDescription=c(
                         "Rack number",
                         "siRNA catalogue number",
                         "siRNA gene symbol",
                         "siRNA EntrezGene ID",
                         "siRNA targeting accession"
                         ))
phData <- new("AnnotatedDataFrame", data=pData, varMetadata=metaData)
x <- parseRTCA(ofile, phenoData=phData)
@ 

\todo{David}{Explain the transformations and discuss}

\section{Manipulation}
\subsection{Smooth Transformation}

<<smoothTransform, echo=TRUE>>=
xSmooth <- smoothTransform(x)
@ 

\subsection{Interpolation Transformation}

<<interpolationTranform, echo=TRUE>>=
xInter <- interpolationTransform(x)
@ 
\section{Methods}
\subsection{Derivative Transformation}
Or known as slope.
<<derivTransform, echo=TRUE>>=
xDeriv <- derivativeTransform(x)
@ 

\subsection{Relative Growth Rate Transformation}
<<rgrTransform, echo=TRUE>>=
xRgr <- rgrTransform(x)
@ 

\section{Discussion}
\todo{David}{To write discussion}

\section{Session Info}
The script runs within the following session:
<<sessionInfo, echo=FALSE, results=tex>>=
toLatex(sessionInfo())
@

\end{document}
